import React, { createContext, useContext, useState, useEffect } from "react";
import axios from "axios";

const StoreContext = createContext();

// Define your backend base URL
const API_BASE_URL = "http://localhost:8080/api/orders";

export const StoreProvider = ({ children }) => {
  const [cart, setCart] = useState([]);
  const [orders, setOrders] = useState([]);

  // --- NEW: Fetch existing pending orders from DB on load ---
  useEffect(() => {
    const fetchOrders = async () => {
      try {
        const response = await axios.get(`${API_BASE_URL}/pending`);
        setOrders(response.data);
      } catch (err) {
        console.error("Error fetching orders:", err);
      }
    };
    fetchOrders();
  }, []);

  const addToCart = (item) => {
    setCart((prev) => {
      const existingItem = prev.find((cartItem) => cartItem.id === item.id);
      if (existingItem) {
        return prev.map((cartItem) =>
          cartItem.id === item.id ? { ...cartItem, qty: cartItem.qty + 1 } : cartItem
        );
      }
      return [...prev, { ...item, qty: 1, price: Number(item.price) }];
    });
  };

  const removeFromCart = (id) => {
    setCart((prev) => prev.filter((item) => item.id !== id));
  };

  // --- UPDATED: Send Order to DB ---
  const sendOrderToKitchen = async () => {
    if (cart.length === 0) return;

    const newOrder = {
      items: cart, // Spring Boot will need to handle this List/Set
      status: "PENDING",
      timestamp: new Date().toISOString()
    };

    try {
      // 1. Post to Spring Boot
      const response = await axios.post(API_BASE_URL, newOrder);
      
      // 2. Update local state with the ID generated by the DB
      setOrders((prev) => [...prev, response.data]);
      setCart([]); // Clear cart only if request succeeds
    } catch (err) {
      console.error("Failed to save order:", err);
      alert("Order failed to send to kitchen. Check backend connection.");
    }
  };

  // --- UPDATED: Update DB Status to 'SERVED' ---
  const completeOrder = async (id) => {
    try {
      // Use PATCH or PUT to update the status in the DB
      await axios.patch(`${API_BASE_URL}/${id}/complete`);
      
      // Remove from the local "Kitchen View" state
      setOrders((prev) => prev.filter((order) => order.id !== id));
    } catch (err) {
      console.error("Failed to complete order:", err);
    }
  };

  return (
    <StoreContext.Provider value={{ cart, orders, addToCart, removeFromCart, sendOrderToKitchen, completeOrder }}>
      {children}
    </StoreContext.Provider>
  );
};

export const useStore = () => useContext(StoreContext);